modLoader="javafml" #junkloader

loaderVersion="*" #From mixin.

license="CC-BY-4.0 License"

issueTrackerURL="https://github.com/KosmX/emotes/issues" #optional

[[mods]] #mandatory
# The modid of the mod
modId="emotecraft"

version="${version}"

displayName="Emotecraft"

#displayURL="https://kosmx.gitbook.io/emotecraft/"
#Forge menu was always trying to open this.

logoFile="emotecraft_mod_logo.png" #optional

authors="KosmX" #optional

description="${description}"

[[mixins]]
config = "emotecraft.mixins.json"
config = "emotecraft-arch.mixins.json"

[[dependencies.emotecraft]]
modId="playeranimator"
mandatory=true
type = "required"
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"